### ISSUE TITLE
The test should mock the get repositories to fake an updated call to the backend.

### ISSUE THREAD

**Issue by ramiroluz** [Rocketseat/gostack-template-conceitos-react-native#3]
The test should mock the get repositories to fake an updated call to the backend.

As a user I want to open the app without any items:
  - Want to add an item.
  - Want to see all the items, including those that where added by someone else.

**Comment by josepholiveira** [comment]
Hey @ramiroluz !

Thank you for the PR, but this "issue" has a purpose. We wan't to make sure that the student doing the challenge use the state of the application to solve the problem, not the API, so it would be a real challenge for a beginner in React.

If you have any questions about it, you can tell me!

**Comment by ramiroluz** [comment]
That's ok. Good to know.

It always depends on the purpose of the app.

**Comment by ramiroluz** [comment]
By the way, the test still checks the other behavior, just mocks the get if someone uses it.
